# Generated by Django 5.2.7 on 2025-10-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=2, help_text='Battery capacity in kWh', max_digits=5)),
                ('epa_range_miles', models.PositiveIntegerField(help_text='EPA estimated range in miles')),
            ],
        ),
    ]
