# Generated by Django 5.2.7 on 2025-10-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evolve_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricvehicle',
            options={'managed': False},
        ),
    ]
