# Generated by Django 5.2.7 on 2025-10-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evolve_site', '0002_alter_electricvehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricvehicle',
            options={'managed': True},
        ),
    ]
