# Generated by Django 5.2.7 on 2025-10-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolve_site', '0003_alter_electricvehicle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricvehicle',
            name='name',
        ),
        migrations.AddField(
            model_name='electricvehicle',
            name='manufacturer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='electricvehicle',
            name='model',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='electricvehicle',
            name='model_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='battery_capacity_kwh',
            field=models.DecimalField(decimal_places=1, help_text='Battery capacity in kWh', max_digits=5),
        ),
        migrations.AlterField(
            model_name='electricvehicle',
            name='epa_range_miles',
            field=models.PositiveIntegerField(db_column='electric_range_miles', help_text='EPA estimated range in miles'),
        ),
        migrations.AlterModelTable(
            name='electricvehicle',
            table='public.vehicles',
        ),
    ]
