# Generated by Django 5.2.7 on 2025-10-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evolve_site', '0004_remove_electricvehicle_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricvehicle',
            options={'managed': False},
        ),
    ]
