# Generated by Django 5.2.7 on 2025-10-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evolve_site', '0005_alter_electricvehicle_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='electricvehicle',
            table='vehicles',
        ),
    ]
