# Generated by Django 5.2.7 on 2025-11-02 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolve_site', '0006_alter_electricvehicle_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level2CalculatorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_model', models.CharField(max_length=100)),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_miles', models.PositiveIntegerField()),
                ('charging_hours', models.PositiveIntegerField()),
                ('home_voltage', models.CharField(choices=[('110', '110V'), ('240', '240V')], max_length=10)),
                ('recommendation', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Level 2 Calculator Submission',
                'verbose_name_plural': 'Level 2 Calculator Submissions',
            },
        ),
    ]
